### ISSUE TITLE
How to disable lookup on artifactshub, when configured nexus repository.

### ISSUE THREAD

**Issue by Shivam0609** [sstarcher/helm-exporter#120]
Trying to use nexus repository in helm-exporter configMap.

Running helm-exporter in EKS, all the helm charts installed are present in our nexus repository.

**Example configuration applied for helm-exporter to override registry**
```
config.yaml: |-
    helmRegistries:
      override:
      - allowAllReleases: false
        charts: []
        registry:
          url: " " ## Path to index.yaml on nexus repository
          secretRef:
            name: "helm-exporter-secret"  # secret having username & password to access nexus
            userKey: "username"
            passKey: "password"
      overrideChartNames: {}
      registryNames: []
```

## What is expected behaviour
helm-exporter should not look for charts information on artifactshub, instead should look into defined nexus repository where we keep our helm charts.

## What team can help with
Is their any configure for helm-exporter to search charts in nexus repository instead of artifactshub to avoid warning in the log.

## Example warning 

```shell
time="2023-08-09T14:12:14Z" level=warning msg="unable to find any charts matching radar on artifacthub" chart=radar
time="2023-08-09T14:12:14Z" level=warning msg="unable to find any charts matching radar on artifacthub" chart=radar
```
