### ISSUE TITLE
ChartMuseum to OCI & index.yaml registry Harbor

### ISSUE THREAD

**Issue by dalvarezquiroga** [sstarcher/helm-exporter#145]
With the latest upgrade of Harbor, chartmuseum got deprecated in favour of OCI registry. 

```
# If the helm charts are not stored on hub.helm.sh then a custom registry can be configured here.
# Currently only index.yaml registry is supported (helm supports other registries as well)
    override:
      - registry:
          url: "https://some.url" # Url to the index file
```
For that reason, the index.yaml file no longer exists... 
The question is, is there a way to make helm-exporter work with the new OCI method?

Thanks!
