### ISSUE TITLE
MULTIPLESCHARTS on Chart, how can we select an especific registry?

### ISSUE THREAD

**Issue by rubeeenrg2002** [sstarcher/helm-exporter#149]
Hello, it's a pleasure @sstarcher.

I explain to you the situation I am facing:

At my company we use the `vault` chart from the `hashicorp` repository (this is at [artifacthub.io](https://artifacthub.io/packages/helm/hashicorp/vault#views)).

The problem it's the following... there is also another chart for `vault` by `bitnami`, as you will see here, I have `bitnami` registred in my `values.yaml` too because we use another charts from `bitnami` so, the exporter says 'MULTIPLESCHARTS' for `vault`:

```
...
config:
  helmRegistries:
    overrideChartNames: {}
    override:
      - registry:
          url: "" 
        charts: []
        allowAllReleases: true
    registryNames:
    - bitnami
    - hashicorp
    ...
    - sstarcher
```

I tried the following to especify that I want the exporter to search `vault` on `hashicorp` registry but doesn't works:

**TEST 1:**

```
...
config:
  helmRegistries:
    overrideChartNames: # {}
      vault: hashicorp/vault
    override:
      - registry:
          url: "" 
        charts: []
        allowAllReleases: true
    registryNames:
    - bitnami
    - hashicorp
    ...
    - sstarcher
```

**TEST 2:**

```
...
config:
  helmRegistries:
    overrideChartNames: # {}
      vault: hashicorp/vault
    override:
      - registry:
          url: "https://helm.releases.hashicorp.com/" 
        charts: # []
          - vault
        allowAllReleases: true
    registryNames:
    - bitnami
    - hashicorp
    ...
    - sstarcher
```

I know that the second try it's not correct because on the `registry` section we have to specify if the registry is not on `artifacthub`, but I wanted to try.

How can we manage this?

**Comment by rubeeenrg2002** [comment]
Also, I would know if it's posible to "skip" charts thare are not in artifcuthub, I mean, with the dashboard in grafana, only see the charts thar are from artifacthub

**Comment by sstarcher** [comment]
I don't believe this is currently possible without a feature change.

**Comment by sstarcher** [comment]
I don't believe either is currently possible, but the second one should be fairly easy to implement.  You could likely also filter by the fact that it does not haver an update version.  Or are you trying to just remove the extra metrics?

**Comment by rubeeenrg2002** [comment]
I'm trying to remove just the Charts that are made / modified by us, for example:

![image](https://github.com/sstarcher/helm-exporter/assets/155071533/6990a4e3-357d-4386-b91c-4e35538f6e1a)

I only want to see on Grafana the Charts that are from `artifacthub` and skip these modified Charts.

**Comment by alexeyklots** [comment]
> Hello, it's a pleasure @sstarcher.
> 
> I explain to you the situation I am facing:
> 
> At my company we use the `vault` chart from the `hashicorp` repository (this is at [artifacthub.io](https://artifacthub.io/packages/helm/hashicorp/vault#views)).
> 
> The problem it's the following... there is also another chart for `vault` by `bitnami`, as you will see here, I have `bitnami` registred in my `values.yaml` too because we use another charts from `bitnami` so, the exporter says 'MULTIPLESCHARTS' for `vault`:
> 
> ```
> ...
> config:
>   helmRegistries:
>     overrideChartNames: {}
>     override:
>       - registry:
>           url: "" 
>         charts: []
>         allowAllReleases: true
>     registryNames:
>     - bitnami
>     - hashicorp
>     ...
>     - sstarcher
> ```
> 
> I tried the following to especify that I want the exporter to search `vault` on `hashicorp` registry but doesn't works:
> 
> **TEST 1:**
> 
> ```
> ...
> config:
>   helmRegistries:
>     overrideChartNames: # {}
>       vault: hashicorp/vault
>     override:
>       - registry:
>           url: "" 
>         charts: []
>         allowAllReleases: true
>     registryNames:
>     - bitnami
>     - hashicorp
>     ...
>     - sstarcher
> ```
> 
> **TEST 2:**
> 
> ```
> ...
> config:
>   helmRegistries:
>     overrideChartNames: # {}
>       vault: hashicorp/vault
>     override:
>       - registry:
>           url: "https://helm.releases.hashicorp.com/" 
>         charts: # []
>           - vault
>         allowAllReleases: true
>     registryNames:
>     - bitnami
>     - hashicorp
>     ...
>     - sstarcher
> ```
> 
> I know that the second try it's not correct because on the `registry` section we have to specify if the registry is not on `artifacthub`, but I wanted to try.
> 
> How can we manage this?

Hi @rubeeenrg2002 ,

We have a similar issue I believe. This is how we fix it:
```yaml
config.yaml: |
    helmRegistries:
      override:
        - registry:
            url: "https://helm.releases.hashicorp.com/" 
          charts: 
            - vault
        - registry:
            url: https://charts.bitnami.com/bitnami
          charts:
            - fluentd # example
            - # Just list here all your charts that you installed from bitnami
      registryNames:
        - sstarcher
        - # Don't put here bitnami or hashicorp related charts
```

**Comment by alexeyklots** [comment]
> I'm trying to remove just the Charts that are made / modified by us, for example:
> 
> ![image](https://private-user-images.githubusercontent.com/155071533/315279253-6990a4e3-357d-4386-b91c-4e35538f6e1a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQwNTUwMzIsIm5iZiI6MTcxNDA1NDczMiwicGF0aCI6Ii8xNTUwNzE1MzMvMzE1Mjc5MjUzLTY5OTBhNGUzLTM1N2QtNDM4Ni1iOTFjLTRlMzU1MzhmNmUxYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyNVQxNDE4NTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03YTAxZDk5Y2M5NWQ1ODcwNmExZTczZjlkNjI5MmFlYTQ4MzA5NGMyMWJiZmNhY2MzMzk5YjVhYjhlYmEzMGVjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.1472CxrzbbFnYKe9RX3NNSMckKRfFkKsf29UZsOnzaQ)
> 
> I only want to see on Grafana the Charts that are from `artifacthub` and skip these modified Charts.

Than you need to update Grafana dashboard and exclude such homebrew charts

**Comment by rubeeenrg2002** [comment]
Hi alexey, I found it too, I forgot to notify @sstarcher, I put it the same as you:

```
config:
  helmRegistries:
    overrideChartNames: 
    override:
      - registry:
          url: "https://helm.releases.hashicorp.com" 
        charts: 
        - vault
        allowAllReleases: true
      - registry:
          url: "https://grafana.github.io/helm-charts" 
        charts: 
        - grafana
        allowAllReleases: true
...
```

Thank you as well for your notification!

Regards,

Rubén
