### ISSUE TITLE
How to Exclude Specific Helm Charts in Helm Exporter?

### ISSUE THREAD

**Issue by amruthavarshinic** [sstarcher/helm-exporter#173]
We have successfully ignored Helm charts from specific namespaces using:

```
# You can specify namespaces to ignore - comma separated list of regexps
namespacesIgnore: ""
```
Now, we need a way to **ignore specific Helm charts themselves**, irrespective of namespace.

### **Is there a built-in way to exclude specific Helm charts from Helm Exporter processing?**

Additionally, to exclude our private Helm charts from Prometheus metrics, the following approach using metric relabeling works:

```
metricRelabelings:
  - sourceLabels: [chart]
    regex: "overlay-upgrade-data-addon|azure-monitor-logs-addon"
    action: drop
```

While this successfully prevents these charts from appearing in Prometheus, Helm Exporter still queries them, leading to unnecessary log warnings:

```
time="2025-05-12T10:59:14Z" level=debug msg="Fetching version for chart" chart=overlay-upgrade-data-addon
time="2025-05-12T10:59:14Z" level=warning msg="unable to find any charts matching overlay-upgrade-data-addon on artifacthub" chart=overlay-upgrade-data-addon
```

Would appreciate any guidance on **how to properly exclude charts at the Helm Exporter level**. Thanks!!
