### ISSUE TITLE
Adding Basic Auth to access Helm repo

### ISSUE THREAD

**Issue by DomenicoS-sdet** [sstarcher/helm-exporter#41]
Hi,

Great idea the override, however it returns a 401 Unauthorised  if the repo has authentication implemented (like mine). I cloned the code and added a basic Authentication to the Get request to download the index.yaml file from the override, and now I am able to get the file.

Below an example of the config.yaml file, where for each Helm repo it is possible to specify its own authentication as Env variables. These can then be passed as k8s secret, or CI env variable at deploy.

```yaml
helmRegistries:
  override:
    - registry:
        url: "https://private.chart.museum/index.yaml"
      charts:
        - chart_one
        - chart_two
      usernameEnvName: OVERRIDE_HELM_USER
      passwordEnvName: OVERRIDE_HELM_PSW
      allowAllReleases: true
```

Then the code for the new request is quite easy
```Go
req, err := http.NewRequest(http.MethodGet, r.HelmRegistry.URL, nil)
	if err != nil {
		log.WithError(err).Error("failed to get chart info")
	}
	u, ok := os.LookupEnv(r.UsernameEnvName)
	p, ok := os.LookupEnv(r.PasswordEnvNam)
	if ok {
		req.SetBasicAuth(u, p)
	}
	resp, err := client.Do(req)
```

If it sounds sensible I can open a PR with all the changes to introduce the authentication
