### ISSUE TITLE
Adding proxy support

### ISSUE THREAD

**Issue by panzouh** [sstarcher/helm-exporter#53]
It would be really nice if proxy support was available for on-prem architecture like bellow (or at least env values) :
```yaml
proxy:
  enabled: true
  httpProxy: http://my-proxy:8080
  httpsProxy: http://my-proxy:8080
```
and that in [deployment.yaml](https://github.com/sstarcher/helm-exporter/blob/master/helm/templates/deployment.yam) : 
```yaml
{{- if.Values.proxy.enabled }}
env:
  - name: no_proxy
    value: localhost
  - name: http_proxy
     value: {{ .Values.proxy.httpProxy }}
  - name: https_proxy
     value: {{ .Values.proxy.httpsProxy }}
{{- end }}
```
