### ISSUE TITLE
no such file or directory

### ISSUE THREAD

**Issue by ElfoLiNk** [sstarcher/helm-exporter#84]
Hello,
I'm trying the following setup:

```
    override:
      - registry:
          url: "https://solr.apache.org/charts/index.yaml"
        charts:
          - solr
        allowAllReleases: false
```

But i see in the logs the following log

```
level=warning msg="open /.cache/helm/repository/solr-index.yaml: no such file or directory"
```
